### PR TITLE
Tests for Completion setters/getters and Completion::toArray exception

### LINKED ISSUE #225: Test missing for DSL\Suggester\Completion
https://github.com/ongr-io/ElasticsearchBundle/blob/master/DSL/Suggester/Completion.php

### PR DESCRIPTION
**Pull request by AndriusBil**
Closes #225

### CODE REVIEW

File: Tests/app/fixture/AbstractEntityTest.php [hunk 1]
```diff
@@ -0,0 +1,269 @@
...
+ *
+ * (c) NFQ Technologies UAB <info@nfq.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace ONGR\ElasticsearchBundle\Tests\app\fixture;
+
+use PHPUnit_Framework_MockObject_MockObject;
```
Comment (saimaz) [inline Tests/app/fixture/AbstractEntityTest.php]: No need to define use case like this.

File: Tests/app/fixture/AbstractEntityTest.php [hunk 2]
```diff
@@ -0,0 +1,269 @@
...
+/*
+ * This file is part of the ONGR package.
+ *
+ * (c) NFQ Technologies UAB <info@nfq.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace ONGR\ElasticsearchBundle\Tests\app\fixture;
```
Comment (saimaz) [inline Tests/app/fixture/AbstractEntityTest.php]: Are you sure it is the right namespace and place for such a kind `abstract` test? Do we need this test class at all?

File: Test/EncapsulationTestAwareTrait.php [hunk 3]
```diff
@@ -0,0 +1,277 @@
...
+        $setter = 'set' . ucfirst($field);
+        $getter = 'get' . ucfirst($field);
+
+        if ($type === 'boolean') {
+            $getter = 'is' . ucfirst($field);
+        }
+
+        $stub = $this->getStub();
+
+        if (!isset($stub)) {
```
Comment (tautrimas) [inline Test/EncapsulationTestAwareTrait.php]: This seem to be always `false`.

Comment (AndriusBil) [inline Test/EncapsulationTestAwareTrait.php]: isset() will return FALSE if testing a variable that has been set to NULL (php.net manual).
$this->stub is set to null by default. In case we don't change $this->stub value !isset($this->stub) should generate true. Or am I getting something wrong ?

Comment (tautrimas) [inline Test/EncapsulationTestAwareTrait.php]: OK, then simply do `$stub === null` check.

File: Test/EncapsulationTestAwareTrait.php [hunk 4]
```diff
@@ -0,0 +1,277 @@
...
+ */
+
+namespace ONGR\ElasticsearchBundle\Test;
+
+/**
+ * A helper for testing setters/getters.
+ *
+ * Trait EncapsulationTestAwareTrait
+ */
+trait EncapsulationTestAwareTrait
```
Comment (tfe2012) [inline Test/EncapsulationTestAwareTrait.php]: why you use trait instead of abstract class?

Comment (AndriusBil) [inline Test/EncapsulationTestAwareTrait.php]: There might be scenarios, where we need to test encapsulation, but we're already using abstraction class.
